spring.application.name=employee
server.servlet.context-path=/employee-service

# Use H2 in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Automatically create/update tables based on JPA entities
spring.jpa.hibernate.ddl-auto=update

# Enable H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
